#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.9.6 on Sat Aug  8 15:55:55 2020
#

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode
# end wxGlade


class CCFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: CCFrame.__init__
        kwds["style"] = kwds.get("style", 0) | wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.SetSize((557, 395))
        
        # Menu Bar
        self.frame_menubar = wx.MenuBar()
        self.fileMenu = wx.Menu()
        self.frame_menubar.doThingItem = self.fileMenu.Append(wx.ID_ANY, "DoThing", "\"Help string goes here for DoThing\"")
        self.Bind(wx.EVT_MENU, self.onDoThing, id=self.frame_menubar.doThingItem.GetId())
        self.frame_menubar.exitItem = self.fileMenu.Append(wx.ID_EXIT, "Quit", "\"Exit the application.\"")
        self.Bind(wx.EVT_MENU, self.onExit, id=wx.ID_EXIT)
        self.frame_menubar.Append(self.fileMenu, "&File")
        self.helpMenu = wx.Menu()
        item = self.helpMenu.Append(wx.ID_ANY, "&Help (Online)", "Access online help.")
        self.Bind(wx.EVT_MENU, self.onHelp, id=item.GetId())
        self.frame_menubar.aboutItem = self.helpMenu.Append(wx.ID_ABOUT, "About", "")
        self.Bind(wx.EVT_MENU, self.onAbout, id=wx.ID_ABOUT)
        self.frame_menubar.Append(self.helpMenu, "&Help")
        self.SetMenuBar(self.frame_menubar)
        # Menu Bar end
        self.statusBar = self.CreateStatusBar(2)
        self.inputBoxName = wx.TextCtrl(self, wx.ID_ANY, "John Hancock")
        self.button1 = wx.Button(self, wx.ID_ANY, "Update Server")
        self.input2Box = wx.TextCtrl(self, wx.ID_ANY, "John Hancock")
        self.button2 = wx.Button(self, wx.ID_ANY, "Update Server")
        self.logText = wx.TextCtrl(self, wx.ID_ANY, "", style=wx.HSCROLL | wx.TE_MULTILINE | wx.TE_READONLY)

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_BUTTON, self.onPress, self.button1)
        self.Bind(wx.EVT_BUTTON, self.onPress, self.button2)
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: CCFrame.__set_properties
        self.SetTitle("Control Client")
        self.SetBackgroundColour(wx.Colour(101, 101, 101))
        self.statusBar.SetStatusWidths([-1, -1])

        # statusbar fields
        statusBar_fields = ["statusBar", "stuff"]
        for i in range(len(statusBar_fields)):
            self.statusBar.SetStatusText(statusBar_fields[i], i)
        self.inputBoxName.SetMinSize((200, -1))
        self.inputBoxName.SetToolTip("Enter your name here.")
        self.inputBoxName.SetFocus()
        self.input2Box.SetMinSize((200, -1))
        self.input2Box.SetToolTip("Enter your name here.")
        self.input2Box.SetFocus()
        self.logText.SetBackgroundColour(wx.Colour(81, 81, 81))
        self.logText.SetForegroundColour(wx.Colour(204, 204, 204))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: CCFrame.__do_layout
        topSizer = wx.BoxSizer(wx.VERTICAL)
        sizerLogs = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Logs"), wx.VERTICAL)
        sizerInputs = wx.StaticBoxSizer(wx.StaticBox(self, wx.ID_ANY, "Inputs"), wx.VERTICAL)
        sizerInput2 = wx.BoxSizer(wx.HORIZONTAL)
        sizerInput1 = wx.BoxSizer(wx.HORIZONTAL)
        nameInputLabel = wx.StaticText(self, wx.ID_ANY, "Your Name", style=wx.ALIGN_RIGHT)
        nameInputLabel.SetMinSize((100, -1))
        sizerInput1.Add(nameInputLabel, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 4)
        sizerInput1.Add(self.inputBoxName, 1, wx.FIXED_MINSIZE, 0)
        sizerInput1.Add(self.button1, 0, 0, 0)
        sizerInputs.Add(sizerInput1, 0, wx.ALL | wx.EXPAND, 5)
        input2Label = wx.StaticText(self, wx.ID_ANY, "Stuff", style=wx.ALIGN_RIGHT)
        input2Label.SetMinSize((100, -1))
        sizerInput2.Add(input2Label, 0, wx.ALIGN_CENTER_VERTICAL | wx.RIGHT, 4)
        sizerInput2.Add(self.input2Box, 1, wx.FIXED_MINSIZE, 0)
        sizerInput2.Add(self.button2, 0, 0, 0)
        sizerInputs.Add(sizerInput2, 0, wx.ALL | wx.EXPAND, 5)
        topSizer.Add(sizerInputs, 1, wx.ALL | wx.EXPAND, 5)
        sizerLogs.Add(self.logText, 1, wx.ALL | wx.EXPAND, 4)
        topSizer.Add(sizerLogs, 1, wx.EXPAND, 0)
        self.SetSizer(topSizer)
        self.Layout()
        # end wxGlade

    def onDoThing(self, event):  # wxGlade: CCFrame.<event_handler>
        print("Event handler 'onDoThing' not implemented!")
        event.Skip()

    def onExit(self, event):  # wxGlade: CCFrame.<event_handler>
        print("Event handler 'onExit' not implemented!")
        event.Skip()

    def onHelp(self, event):  # wxGlade: CCFrame.<event_handler>
        print("Event handler 'onHelp' not implemented!")
        event.Skip()

    def onAbout(self, event):  # wxGlade: CCFrame.<event_handler>
        print("Event handler 'onAbout' not implemented!")
        event.Skip()

    def onPress(self, event):  # wxGlade: CCFrame.<event_handler>
        print("Event handler 'onPress' not implemented!")
        event.Skip()

# end of class CCFrame

class ControlClientApp(wx.App):
    def OnInit(self):
        self.ccframe = CCFrame(None, wx.ID_ANY, "")
        self.SetTopWindow(self.ccframe)
        self.ccframe.Show()
        return True

# end of class ControlClientApp

if __name__ == "__main__":
    ccApp = ControlClientApp(0)
    ccApp.MainLoop()
