# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import helloWorld_pb2 as helloWorld__pb2


class helloRPCStub(object):
    """Defines the service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.sendRequest = channel.unary_unary(
                '/helloRPC.helloRPC/sendRequest',
                request_serializer=helloWorld__pb2.helloRequest.SerializeToString,
                response_deserializer=helloWorld__pb2.helloReply.FromString,
                )


class helloRPCServicer(object):
    """Defines the service
    """

    def sendRequest(self, request, context):
        """Function invoked to send the request
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_helloRPCServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'sendRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.sendRequest,
                    request_deserializer=helloWorld__pb2.helloRequest.FromString,
                    response_serializer=helloWorld__pb2.helloReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'helloRPC.helloRPC', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class helloRPC(object):
    """Defines the service
    """

    @staticmethod
    def sendRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/helloRPC.helloRPC/sendRequest',
            helloWorld__pb2.helloRequest.SerializeToString,
            helloWorld__pb2.helloReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
